name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ secrets.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore src/ServiceHub/ServiceHub.sln

      - name: Setup DB
        shell: pwsh
        run: |
            cd src/ServiceHub/
            chmod +x migrate.ps1
            .\migrate.ps1

      - name: Build Project
        run: dotnet build src/ServiceHub/ServiceHub.sln --configuration Release --no-restore

      - name: Publish to folder
        run: dotnet publish src/ServiceHub/ServiceHub.sln --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
